### ISSUE TITLE
VSCode 常用插件（不定期更新）

### ISSUE THREAD

**Issue by chiehw** [chiehw/blog#4]
# 写代码通用

- [todo tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree)：可以快速浏览代码中的 todo
- [Material Icon Theme](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)：左侧文件目录的 icon，更容易辨识。
- ~~[Better Comments](https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments)~~：更人性化的注释。看 lib 的注释会很难看。
- [Image Preview](https://marketplace.visualstudio.com/items?itemName=kisstkondoros.vscode-gutter-preview)：预览图片。

**Comment by asur4s** [comment]
# Rust

- rust-analyzer： Rust 语言服务器。
- TabNine：自动补全。
- better-toml：toml 语法高亮。
- crates：在 cargo.toml 显示依赖包的最新版本，也提供了快速升级的入口。
- CodeLLDB：提供一些调试功能。

**Comment by asur4s** [comment]
# Flutter

- [Awesome Flutter Snippets](https://marketplace.visualstudio.com/items?itemName=Nash.awesome-flutter-snippets)：生成常用的 Flutter 样板代码。
- Flutter：提供 Flutter 语言的格式化等。

**Comment by asur4s** [comment]
# Git

- GitLens：实时显示每行代码的提交历史记录；
- Git Graph：查看提交树和文件差异。

**Comment by asur4s** [comment]
## RA 配置

`setting.json`
```json
"[rust]": {
    "editor.defaultFormatter": "rust-lang.rust-analyzer",
    "editor.formatOnSave": "true"
},
"rust-analyzer.checkOnSave.command": "clippy",
"rust-analyzer.cargo.buildScripts.enable": false,
```
