### ISSUE TITLE
配置 Linux 环境（不定期更新）

### ISSUE THREAD

**Issue by chiehw** [chiehw/blog#5]
# Flutter

不推荐使用 snap 安装 Flutter，可能会出现某些奇怪的问题。

```bash
# 创建开发工具的文件夹。
mkdir ~/dev

# 下载最新 Flutter：https://flutter.cn/docs/development/tools/sdk/releases
wget https://storage.flutter-io.cn/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.9-stable.tar.xz

# 将 flutter 工具添加到环境变量中
echo 'export PATH="$PATH:$HOME/dev/flutter/bin"' >> ~/.bashrc && source ~/.bashrc


```

**Comment by asur4s** [comment]
# Proxy

## Git
```bash
git config --global http.proxy http://192.168.1.1:7890
git config --global https.proxy http://192.168.1.1:7890
```

## Rust

```bash

vim ~/.cargo/config
<< EOF
[http]
proxy = "192.168.1.1:7890"
[https]
proxy = "192.168.1.1:7890"
EOF
```

**Comment by chiehw** [comment]
# Docker 
-  安装：https://yeasy.gitbook.io/docker_practice/install/ubuntu#qi-dong-docker
- 代理：https://cloud.tencent.com/developer/article/1806455

**Comment by chiehw** [comment]
```bash
 sudo apt install openssh-server
```

**Comment by chiehw** [comment]
https://github.com/chiehw/weekly/blob/main/archive-blog/2022/10.md

**Comment by chiehw** [comment]
# Rsync

```
rsync -avhn --delete local/ remote/
```

- -a archive mode
- -v increase verbosity
- -h output numbers in a human-readable format
- -n dry run, perform a trial run with no changes made. Always use this flag initially to prevent data loss. When you are happy, remove it.
